### ISSUE TITLE
`No JSON object could be decoded` when attempting to deploy forms

### ISSUE THREAD

**Issue by janknobloch** [kobotoolbox/kobo-docker#162] opened 2018-02-12 22:08 UTC
Hey there,

just installed a fresh version (ea4a8ff) from (d2b16df) of kobo and turns out form deployment is broken: (No JSON object could be decoded -> log file below)

(Updating an existing kobo to the new revision works, however removing my containers + .vols -> and pulling the update leads to the same issue occuring afterwards)

It seems it has to do with the postgre database select / insert as this is the error from the logs:
`postgres_1        | 2018-02-12 21:59:02 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2018-02-12 21:59:02 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1`

Looks like a similar issue that has been there before #134 
I logged into the running postgre container and indeed "koboform_surveydraft" is not existent.

Looking forward to see this fixed soon as kobo is broken for me right now.

Running Ubuntu xenial -> server settings config with letsencrypt certs.

Best
 #Jan

**Comment by aurdipas** [comment] 2018-02-13 09:14
same issue for me. 
postgres_1        | 2018-02-13 09:05:10 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2018-02-13 09:05:10 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1

**Comment by janknobloch** [comment] 2018-02-13 09:19
thx for sharing. I tried to nail down the issue by trying the following things, sadly without success:

1. pulling an older git revision from june and rebuild all containers / images. (no success)
2. replacing the postgre container and enketo_express container with older revisions. (no success)
postgre:batman + enketo_express (without widgets) (no success)
3. trying to add host name resolution into extras as stated in #134  (no success)

Would be glad if any dev could have a closer look at this. Interestingly enough updating my other server to the new revision did not show the same issue, only after a fresh install. Maybe the database creation script is not creation the tables properly anymore?

**Comment by janknobloch** [comment] 2018-02-13 17:27
@aurdipas 
I could fix the issue after of a full day of investigation... It turns out that all new images of kobocat docker container are leading to this issue. So you have to replace the following image link inside your docker-compose.yml:
from:
`kobocat:
  image: kobotoolbox/kobocat:latest`
to:
`kobocat:
  image: kobotoolbox/kobocat:issue_222`

turns out the last images namely are all broken at least for deployment:

- 2.018.06a
- latest
- 2.017.46
- unhcr-20171103
- unhcr-20170807

Which means im going to use a kobocat image which is nearly two years old, but at least it works..
Lets see if one of the contributers has a word on this anytime soon..

**Comment by jnm** [comment] 2018-02-13 17:58
Hello,

@aurdipas, `relation "koboform_surveydraft" does not exist` is confusing noise but not the root cause of this problem as far as we know. See https://github.com/kobotoolbox/kobo-docker/issues/134.

@janknobloch, please:
1. Set `KOBOCAT_DJANGO_DEBUG` to `True` in `envfiles/kobocat.txt`;
1. Cause the `No JSON object could be decoded` error again;
1. If possible, stop making requests to this server (to make log reading easier);
1. Find the last exception in `log/kobocat/uwsgi.log`;
1. Paste the full traceback here.

I'm confused about a few things:

* What repository are you talking about when you mention `fresh version (ea4a8ff) from (d2b16df) of kobo`? I don't see those hashes in `kobo-docker` or `kobocat`, and you mention that versions of `kobocat` less than "nearly two years old" break your installation.
* What is `postgre:batman`?

**Comment by janknobloch** [comment] 2018-02-13 18:29
Hey @jnm,

thanks for looking into this.

Let me first explain a bit to remove confusion:
The hashes im referring to are the ones you see when you login to koboform.server.tld

As I cant refer easily to the patchwork of versions of the exiting docker-kobo containers out there.
Locally they are all tagged as latest however I had to go through 20 different images kobocat, poestgre, etc. to find a constellation where the issue is not in.

Also I find it very hard after one full day of looking into the codebase to give detailed information for the following reasons:

1. Your Github commits / tags don't go together with your docker image commits at all:
This leads to the following situation:

1. You pull this github repository on one day lets say commit id: XXXX
2. Developers change docker images which you then pull with: docker-compose pull (as recommended to keep ngix etc up to date -> this then suddenly breaks the whole deployment process) So you could mean that you want to lookup the commit ID XXXX to rollback to the commit before. But you cant as the docker tags are somewhat not transparent to me.
3. So I cant do a rollback on the docker-containers easily as i don't have references on the "latest" images I pulled before updating them with the newest "latest" from docker hub.
4. In addition the docker images get a weird tag e.g. kobotoolbox/postgre:batman for example for the postgre image. or e.g. kobotoolbox/kobocat:unhcr-20171103 for the kobocat image.

All I can say for now is that the latest docker images you have compiled (running docker-compose pull) as a single unit, which also gets pulled on a fresh install of this github repository are only running well together if you downgrade kobocat:latest to kobocat:issue_222. At least for me. I think this will hold for others too. As mentioned above updating was not an issue but a fresh install was, i dont know why?

Coming to your question "nearly two years old":
If you lookup the kobocat_issue_222 version (the only one that runs for me with the other latest images): [https://hub.docker.com/r/kobotoolbox/kobocat/tags/](https://hub.docker.com/r/kobotoolbox/kobocat/tags/) it turns out that this version is about 2 years old if im not mistaken.

Steps to reproduce this error are the following:

- remove all docker container
- remove all docker images
- remove your .vols folder (as it seems if the database is there from previous version no error occurs)
- remove or update this pulled git repository to the newest version
- run docker-compose pull
- setup ssl as usual
- modify your server.yml as usual
- docker-compose up
- create simple random form and try to deploy

I will gladly follow your advice and update the kobocat container again to the latest version on another server when i find the time in the next couple of days and will send you the logs for investigation. Sadly im in Africa right now doing a pilot study using kobo and thats why I needed a short term quick fix.

Best and thanks for helping out.
Jan

**Comment by jnm** [comment] 2018-02-14 01:10
This is good feedback; thanks. Best of luck with your pilot study. I'll look forward to receiving your uWSGI logs.

**Comment by janknobloch** [comment] 2018-02-14 16:12
@jnm 
no errors in the logfile:
`*** Operational MODE: preforking ***
DEBUG 2018-02-14 16:07:38,949 base 87 140182865745728 Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f7ebbfdebd0>
INFO 2018-02-14 16:07:38,950 base 87 140182865745728 Raven is not configured (logging is disabled). Please see the documentation for more information.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xde5ad0 pid: 87 (default app)
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 87)
spawned uWSGI worker 1 (pid: 101, cores: 1)
spawned uWSGI worker 2 (pid: 102, cores: 1)
[pid: 101|app: 0|req: 1/1] 172.17.0.1 () {48 vars in 817 bytes} [Wed Feb 14 16:08:00 2018] POST /api/v1/forms => generated 206058 bytes in 13818 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)
[pid: 101|app: 0|req: 2/2] 172.17.0.1 () {48 vars in 817 bytes} [Wed Feb 14 16:08:54 2018] POST /api/v1/forms => generated 206058 bytes in 708 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)

`

Issue remains. Interestringly enough it only occours if i clean my database folders completely. (.vols) if i add a single form/project on the old version and than do an update the error does not occur also not for new forms.
Any other log I should check?

**Comment by arnaullopxirau** [comment] 2018-02-19 11:53
Hi, I don't know if it helps, but after installing the latest, downgrading to issue_222 I can deploy forms but other things are broken (ie users management, can't delete users).

**Comment by janknobloch** [comment] 2018-02-19 13:43
You should be able to upgrade to newest version after first deployment. As the database tables get created properly. This worked for me st least.

So workaround newest version with issue222 create one deployment the upgrade.
Cheers
Jan

**Comment by kulkasindia** [comment] 2018-03-09 05:14
I have the same issue,
Thank you @janknobloch you save my life.

I change kobotoolbox/kobocat:latest to kobotoolbox/kobocat:issue_222 in docker-compose.yml and run docker-compose pull
i run docker-compose up -d try to deploy project, and its working.

Then i change back to kobotoolbox/kobocat:latest again.
Now its working. Thank you

**Comment by janknobloch** [comment] 2018-03-09 07:43
Most welcome, this bugged me for a while too.

Good luck with your project.

Best 
Jan

**Comment by cristiandlr** [comment] 2018-04-09 16:17
@janknobloch I just tried your solution, but I'm getting the following error:

Pulling kobocat (kobotoolbox/kobocat:issue_222)...
ERROR: manifest for kobotoolbox/kobocat:issue_222 not found

Any advice?

**Comment by jnm** [comment] 2018-04-09 18:11
I'm going to work on resolving this problem today.

**Comment by janknobloch** [comment] 2018-04-09 18:12
Hey, 
Im not able to check this right now but did you check on docker hub if the version “issue_222” is still available?

Best
Jan

**Comment by cristiandlr** [comment] 2018-04-09 18:25
@janknobloch Hi, checking at https://hub.docker.com/r/kobotoolbox/kobocat/tags/
It's not.
This is the full list of Tags:

latest
2.018.11
2.018.08
2.018.06a
2.017.46
unhcr-20171103
unhcr-20170807

Regards

**Comment by janknobloch** [comment] 2018-04-09 18:29
Than it has been removed, I hope @jnm can fix this problem for us. 😐
Basically the database creation is not done properly as far as I recall, at least some tables in the MySQL db where missing.

**Comment by cristiandlr** [comment] 2018-04-09 18:32
Ok, lets wait for @jnm 's fix, Thanks!

**Comment by jnm** [comment] 2018-04-10 14:43
Thanks for everyone's patience with this, and to @janknobloch for reporting the problem and helping others with workarounds.

It looks like the breaking change was https://github.com/kobotoolbox/kobocat/commit/6114ae9b1eab7153c54af9af6b028edd7d925080.

## 👉 **To fix your installation**
Until we write a fix that avoids this problem in the first place, please run this command in your `kobo-docker` directory:
`docker-compose exec kobocat chown -R wsgi /srv/src/kobocat`

### How I came to this conclusion
For future reference, and in the spirit of open collaboration, here's the complete process I used to reproduce this and find the root cause:
1. Set up a Linode 1024 instance (1 GB RAM, 1 CPU core, 20 GB disk configured with 512 MB of swap; **warning**: as you'll see below, this was not enough memory) 
    * Ubuntu 16.04.4 LTS
    * Docker version 18.03.0-ce, build 0520e24
    * docker-compose version 1.20.1, build 5d8c71b
1. Added DNS record so `*.issue-162.kbtdev.org` resolved to the IP of the Linode instance
1. Obtained certificate from [Let's Encrypt](https://certbot.eff.org/lets-encrypt/ubuntuxenial-other.html)
    1. `add-apt-repository ppa:certbot/certbot`
       `apt update`
       `apt install certbot`
    1. `certbot certonly --standalone -d kf.issue-162.kbtdev.org -d kc.issue-162.kbtdev.org -d ee.issue-162.kbtdev.org`
    1. Double-checked resulting certificate with `openssl x509 -text -in /etc/letsencrypt/live/kf.issue-162.kbtdev.org/fullchain.pem | grep -A 1 'Subject Alternative'`
1. Cloned this repository: `git clone https://github.com/kobotoolbox/kobo-docker` -> commit `23686b365d520c3e5d37b3df2c63894970a15613`
1. Inside the `kobo-docker` directory:
    1. Symlinked server configuration for Docker Compose: `ln -s docker-compose.server.yml docker-compose.yml`
    1. Pulled the Docker images: `docker-compose pull`
       ```
       docker images
       REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
       kobotoolbox/kpi                            latest              6c1684d8b6ea        23 hours ago        1.57GB
       kobotoolbox/kobocat                        latest              3991302f35dd        8 days ago          1.43GB
       kobotoolbox/rabbit                         latest              4bdede92e074        8 days ago          542MB
       kobotoolbox/mongo                          latest              3a8c25dda589        8 days ago          775MB
       kobotoolbox/postgres                       latest              2c237a7925d6        8 days ago          1.14GB
       kobotoolbox/nginx                          latest              0670d0daba83        8 days ago          555MB
       kobotoolbox/enketo-express-extra-widgets   1.55.6              f95d6d3995c8        3 months ago        841MB
       ```
    1. Modified `envfile.server.txt` to set the following variables:
       ```
       PUBLIC_DOMAIN_NAME=issue-162.kbtdev.org
       KOBOFORM_PUBLIC_SUBDOMAIN=kf
       KOBOCAT_PUBLIC_SUBDOMAIN=kc
       ENKETO_EXPRESS_PUBLIC_SUBDOMAIN=ee
       ENKETO_API_TOKEN=enketo-is-great
       DJANGO_SECRET_KEY=django-is-helpful
       KOBO_SUPERUSER_USERNAME=trouble
       KOBO_SUPERUSER_PASSWORD=shoot
       KOBO_SUPPORT_EMAIL=bounce-me@kbtdev.org
       ```
    1. Created `secrets` directory
    1. Inside `secrets` directory:
        1. `cp /etc/letsencrypt/live/kf.issue-162.kbtdev.org/fullchain.pem ssl.crt`
        1. `cp /etc/letsencrypt/live/kf.issue-162.kbtdev.org/privkey.pem ssl.key`
    1. Started Docker containers in the foreground: `docker-compose up`
    1. Ran out of memory while starting Enketo:
       ```
       enketo_express_1  | /etc/my_init.d/01_setup_enketo.bash: line 12:    10 Killed                  grunt
       enketo_express_1  | *** /etc/my_init.d/01_setup_enketo.bash failed with status 137
       ```
    1. Hit CTRL+C to stop the Docker containers
    1. Verified that it was memory exhaustion by checking `journalctl`: found `Out of memory: Kill process 10311 (grunt) score 384 or sacrifice child`
    1. Added 768 MB of swap to the 512 MB I already had:
       `dd if=/dev/zero of=/extra-swap bs=1M count=768`
       `mkswap /extra-swap`
       `swapon /extra-swap`
    1. Re-ran `docker-compose up`
    1. Waited several minutes for Enketo to build:
        * While building, `https://ee.issue-162.kbtdev.org/` returned `502 Bad Gateway`
        * Once complete, it returned `Enketo Express for KoBo Toolbox is running!`
    1. Logged in to `https://kf.issue-162.kbtdev.org/` as the superuser
    1. Refreshed the page to cope with https://github.com/kobotoolbox/kpi/issues/1692
    1. Created a new form called "test form" with a single text question called "test question"
    1. Saved, closed, and attempted to deploy the form
    1. Received `No JSON object could be decoded` error 👈
    1. Hit CTRL+C to stop the Docker containers
    1. Set `KOBOCAT_DJANGO_DEBUG=True` in `envfiles/kobocat.txt`
    1. Started Docker containers again, this time in the background: `docker-compose up -d`
    1. Waited again for Enketo to finish building
    1. Downloaded the XLS of "test form"
    1. Clicked "Projects (Legacy)"
    1. Uploaded the XLS of "test form"
    1. Saw `OSError at /trouble/` / `[Errno 13] Permission denied: '/srv/src/kobocat/media/trouble'` (`trouble` is my username)
    1. Ran `docker-compose exec kobocat chown -R wsgi /srv/src/kobocat`
    1. Successfully deployed "test form" the usual way, by clicking the "DEPLOY" button

**Comment by janknobloch** [comment] 2018-04-10 14:49
Sweet ! Thanks for reporting this.

So It was a permission error in the end. 

Best
Jan

**Comment by cristiandlr** [comment] 2018-04-10 15:37
@jnm and  @janknobloch Thanks a lot for your help!
Already deployed my form.

**Comment by ivangayton** [comment] 2018-04-10 17:32
Thanks @janknobloch and @jnm ; I've been lurking for the last 24 hours and hoping this would get sorted but not wanting to harass you. We've got a training exercise in Tanzania for which we really wanted to spin up a fresh Kobotoolbox, and this has saved us pretty much just in time. Cheers.

**Comment by jubaco30** [comment] 2018-04-11 22:41
Thank you @jnm and @janknobloch
you save us a lot of time
running the following did the trick
docker-compose exec kobocat chown -R wsgi /srv/src/kobocat

**Comment by BrainWise** [comment] 2018-04-13 14:46
Hi Everyone, I am completely new to KoBo and programming. I designed a form (XLS) and get this error: **unable to deploy

your form cannot be deployed because it contains errors:

No JSON object could be decoded**

This error shows up only during deployment (form uploads alright).  I will appreciate any help.
Thanks

**Comment by jnm** [comment] 2018-04-16 20:47
@BrainWise, please try this and let us know if it works for you:

> Until we write a fix that avoids this problem in the first place, please run this command in your `kobo-docker` directory: `docker-compose exec kobocat chown -R wsgi /srv/src/kobocat`

**Comment by janknobloch** [comment] 2018-04-17 07:53
@jnm 
i think i found the reason for this bug?:

On start i found the following output.

`kobocat_1         | %%%%%%% NOTICE %%%%%%%
kobocat_1         | % To avoid long delays, we no longer reset ownership of media files
kobocat_1         | % every time this container starts. If you have trouble with
kobocat_1         | % permissions, please run the following command inside the
kobocat_1         | % `kobocat` container:
kobocat_1         | %	chown -R "wsgi" "/srv/src/kobocat"
`

I guess someone commented this line out leading to the described issue, as the ownership is never set. I think this line should go into the docker-compose of the kobocat-image:latest. So its executed at least once.

**Comment by rward3182** [comment] 2018-04-23 03:07
Messed around with this solution for a while. 
Make sure:
You are in the correct directory cd '/home/d1/kobo-docker-master' 
Also make sure the container is up 

docker-compose up -d

Then apply this command
docker-compose exec kobocat chown -R wsgi /srv/src/kobocat

**Comment by jnm** [comment] 2018-05-29 19:46
We believe this to be fixed as of https://github.com/kobotoolbox/kobo-docker/pull/178, and the workaround should not be needed anymore. Please reopen if you still have trouble.

**Closed by jnm** 2018-05-29 19:46 UTC
Labels: bug
